export type PageId =
  | 'dashboard'
  | 'master'
  | 'entry'
  | 'masters-config'
  | 'report'
  | 'opinion-poll'

export type EntryModuleId =
  | 'voter'
  | 'booth'
  | 'volunteer'
  | 'event'
  | 'campaign'
  | 'user'
  | 'warroom'
  | 'dashboard'
  | 'alliance'
  | 'keypeople'
  | 'feedback'
  | 'commitment'
  | 'grievance'
  | 'agent-activity'
  | 'field-activity'
  | 'volunteer-activity'
  | 'voter-survey'
  | 'attendance'
  | 'assign-telecalling'
  | 'telecalling-assigned'
  | 'feedback-review'

export type MasterModuleId =
  | 'district'
  | 'constituency'
  | 'ward'
  | 'area'
  | 'booth'
  | 'village'
  | 'scheme'
  | 'issue'
  | 'achievement'
  | 'candidate'
  | 'party'
