export type PageId =
  | 'dashboard'
  | 'master'
  | 'entry'
  | 'masters-config'
  | 'report'
  | 'opinion-poll'
  | 'user-settings'

export type EntryModuleId =
  | 'voter'
  | 'booth'
  | 'volunteer'
  | 'event'
  | 'campaign'
  | 'user'
  | 'warroom'
  | 'dashboard'
  | 'alliance'
  | 'keypeople'
  | 'feedback'
  | 'commitment'
  | 'grievance'
  | 'agent-activity'
  | 'field-activity'
  | 'volunteer-activity'
  | 'voter-survey'
  | 'attendance'
  | 'assign-telecalling'
  | 'telecalling-assigned'
  | 'feedback-review'
  | 'global-search'
  | 'beneficiary'

export type MasterModuleId =
  | 'district'
  | 'constituency'
  | 'ward'
  | 'area'
  | 'booth-master'
  | 'village'
  | 'scheme'
  | 'issue'
  | 'achievement'
  | 'candidate'
  | 'party'
  | 'task-category'
  | 'campaign-activity'
  | 'volunteer-role'
  | 'volunteer-type'
  | 'panchayat'
  | 'union'
